services:
  # FastAPI
  api_server:
    image: module_2_parser_image:latest
    build:
      context: ./module_2_parser_db
      dockerfile: Dockerfile
      args:
        FASTEMBED_CACHE_DIR: ${FASTEMBED_CACHE_DIR:-/tmp/fastembed_cache}
        HF_CACHE_DIR: ${HF_CACHE_DIR:-/tmp/huggingface_cache}
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    environment:
      - HF_HOME=${HF_CACHE_DIR}
      - API_KEY=${API_KEY}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - ./module_2_parser_db/.env
    volumes:
      - ${SHARED_DATA_ROOT}:/data
      - fastembed_cache:${FASTEMBED_CACHE_DIR}
      - hf_cache:${HF_CACHE_DIR}
      - ${MODULE_2_LOGS_ROOT}:/app/logs
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:${API_PORT:-8000}/docs')" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      qdrant:
        condition: service_started
      redis:
        condition: service_healthy

  # Воркер
  worker:
    image: module_2_parser_image:latest
    command: ["taskiq", "worker", "parser_db.broker:broker", "parser_db.worker",
              "--workers", "${TASKIQ_WORKERS:-1}",
              "--max-async-tasks", "${TASKIQ_MAX_ASYNC_TASKS:-1}"]
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=${HF_CACHE_DIR}
      - API_KEY=${API_KEY}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - ./module_2_parser_db/.env
    volumes:
      - ${SHARED_DATA_ROOT}:/data
      - fastembed_cache:${FASTEMBED_CACHE_DIR}
      - hf_cache:${HF_CACHE_DIR}
      - ${MODULE_2_LOGS_ROOT}:/app/logs
    depends_on:
      api_server:
        condition: service_started
      redis:
        condition: service_healthy
      qdrant:
        condition: service_started

  # Векторная БД Qdrant
  qdrant:
    image: qdrant/qdrant:v1.18.3
    ports:
      - "${QDRANT_REST_PORT:-6333}:6333" # REST API
      - "${QDRANT_GRPC_PORT:-6334}:6334" # gRPC
    volumes:
      - qdrant_data:/qdrant/storage

  # Брокер
  redis:
    image: redis:8.10.0-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  qdrant_data:
  redis_data:
  fastembed_cache:
  hf_cache: