line-length = 100
target-version = "py311"

[lint]
select = [
    "E",  # Стандартные ошибки pycodestyle
    "F",  # Ошибки Pyflakes (неиспользуемые импорты/переменные)
    "I",  # Сортировка импортов (isort)
    "UP"  # Обновление старого синтаксиса (pyupgrade)
]
ignore = []

exclude = [
    ".venv",
    ".git",
    "__pycache__",
    "tests",
]